# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CodegenTestApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CodegenTestApp
  pod 'Apollo'

  target 'CodegenTestAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CodegenTestAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
