# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'URLSessionMockerSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for URLSessionMockerSample

end

target 'URLSessionMockerSampleTests' do
  inherit! :search_paths
  # Pods for testing
  pod 'Mocker'

end

target 'URLSessionMockerSampleUITests' do
  inherit! :search_paths
  # Pods for testing
end
